package com.cjbooms.fabrikt.models.jackson

import com.example.validation.models.StringValue
import jakarta.validation.Valid

/**
 * Positive control for [ModelValidationTest]. Deliberately uses the container-level `@Valid`
 * placement that Hibernate Validator 9.1 deprecates, so the test can assert that HV000271
 * is actually observable. Not generated by fabrikt.
 */
internal class LegacyContainerValidModel(
    @field:Valid
    val items: List<StringValue> = emptyList(),
)
