name: Manually Notify Sonatype
# This job is only triggered manually in case the release doesn't show up
on:
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Central of Upload (Manual Staging Promotion)
        run: |
          echo "Querying for open staging repository..."
          RESPONSE=$(curl -s -u "${{ secrets.OSSRH_USER_TOKEN_USERNAME }}:${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}" \
            "https://ossrh-staging-api.central.sonatype.com/manual/search/repositories?ip=any&profile_id=com.cjbooms")
          
          REPO_KEY=$(echo "$RESPONSE" | jq -r '.repositories[0].key')

          if [[ "$REPO_KEY" == "null" ]]; then
            echo "No open repository found"
            exit 1
          fi

          echo "Notifying Sonatype to register repository in Central Publisher Portal..."
          curl -X POST -H "Accept: application/json" \
            -u "${{ secrets.OSSRH_USER_TOKEN_USERNAME }}:${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}" \
            "https://ossrh-staging-api.central.sonatype.com/manual/upload/repository/$REPO_KEY"